.TH PN 1
.SH NAME

pn - a command-line tool for phone number manipulation

.SH SYNOPSIS

.B pn
.I COMMAND
[\fIOPTIONS\fR]
.I INPUT

.SH COMMANDS

.TP
.B info
Displays informations about the phone number given as \fIINPUT\fR. Valid
option: \fB-c\fR.
.TP
.B format
Formats a telephone number to the specified standard (E164 by default), result
on stdout. Valid options: \fB-c\fR, \fB-f\fR.
.TP
.B find
Finds phone number in some text, result on stdout (one line per number found).
Valid options: \fB-c\fR, \fB-f\fR, \fB-l\fR.

.SH OPTIONS

.TP
\fB-c\fR \fICOUNTRY\-CODE\fR
If set, the phone number given in \fIINPUT\fR will be considered as belonging
to the country specified by the 2 uppercase letters \fICOUNTRY\-CODE\fR (e.g.
"FR", "US", ...). If this option is not set, \fBpn\fR will look for numbers in
the international format.
.TP
\fB-f\fR \fIFORMAT\fR
Sets the phone number output format. \fIFORMAT\fR must be one of \fBe164\fR,
\fBint\fR (international), \fBnat\fR (national), or \fBteluri\fR (RFC3966 tel
URI). The default value is \fBe164\fR.
.TP
\fB-l\fR \fILENINECY\fR
Sets the phone number search leninency in \fIINPUT\fR. \fILENINECY\fR must be
one of \fBpossible\fR, \fBvalid\fR, \fBstrict\fR, or \fBexact\fR. The default
value is \fBvalid\fR.
See https://javadoc.io/doc/com.googlecode.libphonenumber/libphonenumber/8.4.1

.SH RETURN STATUS
\fBpn\fR returns 0 on successful operations, 1 if an error occurred (option
error, parsing error).

.SH AUTHOR
Camille Oudot
